### ISSUE TITLE
Windows vs Linux: github Commit Not Found

### ISSUE THREAD

**Issue by pwhittin** [babashka/instaparse-bb#8]
Given the following ```bb.edn``` file:
```clojure
{:deps {io.github.babashka/instaparse-bb {:git/sha "059045f6a8450bda74eb30136ddd2c5475f788d1"}}}
```
and given the following ```.clj``` file named ```instaparse-bb-issue.clj```:
```clojure
(ns instaparse-bb-issue.core
  (:require [instaparse.core :as insta]))

(def as-and-bs
  (insta/parser
   "S = AB*
    AB = A B
    A = 'a'+
    B = 'b'+"))

(clojure.pprint/pprint (as-and-bs "aaaaabbbaaaabb"))
```
Executing ```bb instaparse-bb-issue.clj``` on Windows results in the following error:
```
Error building classpath. Commit not found for io.github.babashka/instaparse-bb in repo https://github.com/babashka/instaparse-bb.git at 059045f6a8450bda74eb30136ddd2c5475f788d1
Exception in thread "main" clojure.lang.ExceptionInfo:  babashka.process.Process@e1bf4a0b
        at babashka.process$check.invokeStatic(process.cljc:111)
        at babashka.process$shell.invokeStatic(process.cljc:677)
        at babashka.impl.deps$add_deps$fn__27995.invoke(deps.clj:107)
        at borkdude.deps$_main.invokeStatic(deps.clj:1058)
        at borkdude.deps$_main.doInvoke(deps.clj:888)
        at clojure.lang.RestFn.applyTo(RestFn.java:140)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at babashka.impl.deps$add_deps$fn__28002$fn__28003.invoke(deps.clj:113)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:428)
        at babashka.impl.deps$add_deps$fn__28002.invoke(deps.clj:113)
        at babashka.impl.deps$add_deps.invokeStatic(deps.clj:113)
        at babashka.main$exec$fn__32902.invoke(main.clj:878)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:428)
        at babashka.main$exec.invokeStatic(main.clj:831)
        at babashka.main$main.invokeStatic(main.clj:1223)
        at babashka.main$main.doInvoke(main.clj:1167)
        at clojure.lang.RestFn.applyTo(RestFn.java:140)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at babashka.main$_main.invokeStatic(main.clj:1255)
        at babashka.main$_main.doInvoke(main.clj:1247)
        at clojure.lang.RestFn.applyTo(RestFn.java:140)
        at babashka.main.main(Unknown Source)
        at java.base@22/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```
Executing ```bb instaparse-bb-issue.clj``` on Linux results in the following correct output:
```
[:S
 [:AB [:A "a" "a" "a" "a" "a"] [:B "b" "b" "b"]]
 [:AB [:A "a" "a" "a" "a"] [:B "b" "b"]]]
```
The Linux version information is:
```bash
Linux pauwhi-XPS-15-9500 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Babashka v1.4.192 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (clojure-version)
"1.12.0-SCI"
```
The Windows version information is:
```bash
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045

Babashka v1.4.192 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> (clojure-version)
"1.12.0-SCI"
```

**Comment by borkdude** [comment]
Can't reproduce in Windows 11:

```
C:\Users\borkdude\temp>bb script.clj
[:S
 [:AB [:A "a" "a" "a" "a" "a"] [:B "b" "b" "b"]]
 [:AB [:A "a" "a" "a" "a"] [:B "b" "b"]]]
```

**Comment by pwhittin** [comment]
I was running ```bb``` in a ```Cygwin terminal```, and it was causing this issue.  

I tested it in ```Powershell``` and ```CMD```, and there is no issue.

I terminated my ```Cygwin terminal```, restarted it, and now there is no issue.

I have no idea what was causing the original issue!
